### ISSUE TITLE
fabric8 kubernetes java client support

### ISSUE THREAD

**Issue by RisingPhorce** [voyagermesh/voyager#1199]
Hello.  I found the official Java client for voyager here:  https://github.com/voyager-client/java

This appears to use the official kubernetes-client project.  Our project uses the Fabric8 Kubernetes Java client.  We like the fluent DSL in favor of the official client that tends to have long parameters lists that are often mostly NULL.  

I believe I could use the official voyager java client but there would be some overhead in multiple clients (fabric8 and voyager) and their associated thread pools for http calls.  Would it be possible to generate a fabric8 kubernetes client?  

I'm going to try to take the models from the voyager project and see if fabric8 can declare a client and use the models.

**Comment by tamalsaha** [comment]
Thanks @RisingPhorce . Is there some sort of generator magic for the fabric8 client?

**Comment by RisingPhorce** [comment]
I'm a bit new to their client but here's their CRD example:  https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java

I installed voyager from the provided shell command.  So getting the crd definition works fine. 

```
CustomResourceDefinitionList crds = client.customResourceDefinitions().list();
      List<CustomResourceDefinition> crdsItems = crds.getItems();
      System.out.println("Found " + crdsItems.size() + " CRD(s)");
      CustomResourceDefinition dummyCRD = null;
      for (CustomResourceDefinition crd : crdsItems) {
        ObjectMeta metadata = crd.getMetadata();
        if (metadata != null) {
          String name = metadata.getName();
          System.out.println("    " + name + " => " + metadata.getSelfLink());
        }
}
```

But, declaring the client, in particular this line: 

```
NonNamespaceOperation<Dummy, DummyList, Do
neableDummy, Resource<Dummy, DoneableDummy>> dummyClient = client.customResources(dummyCRD, Dummy.class, DummyList.class, DoneableDummy.class).inNamespace(namespace);
```

seems like it would need models to work with.  I was hoping not to have to reverse engineer all the crd fields and types.
