### ISSUE TITLE
Voyager pods are destroyed and recreated without any clear reason.

### ISSUE THREAD

**Issue by davinchia** [voyagermesh/voyager#1284]
We recently upgrade our Voyager deployment from 5.0.0 to 7.4. We ran the 7.4 install script and deleted the old operator pod. We also updated our ingresses with 7.4 compatible annotations. The initial upgrade went well. 

We are however, noticing some weird behaviour. The Voyager deploy rolls at random, without any manual intervention or ingress updates.  Because connections are properly transferred, no downtime results. This isn't an urgent problem per se, but its strange behaviour that may cause issues down the line.

Any ideas? Perhaps we didn't upgrade Voyager properly and some resources are in conflict?

**Comment by davinchia** [comment]
Any ideas @tamalsaha?

**Comment by tamalsaha** [comment]
My guess is that you are https://github.com/appscode/voyager/issues/1251 problem. Are you using that annotation?

**Comment by davinchia** [comment]
We are not. These are our annotations:
```
  annotations:
    kubernetes.io/ingress.class: voyager

    ingress.appscode.com/type: NodePort
    ingress.appscode.com/force-service-port: "true"

    # Open HAProxy stats on port 56789 by default
    # NOTE(jmodes): access stats via
    # kubectl port-forward $(kubectl get pod -o=name -lorigin-name=rlcdn | awk -F/ '{print $2}' | head -1) 56789
    ingress.appscode.com/stats: "true"

    # Set up Prometheus scraping
    ingress.appscode.com/monitoring-agent: "coreos-prometheus-operator"
    ingress.appscode.com/service-monitor-labels: |
      {
        "prometheus": "pub-haproxy"
      }
    ingress.appscode.com/service-monitor-namespace: "default"
    ingress.appscode.com/service-monitor-endpoint-port: "56790"

    # For configuring options, see the following:
    # https://github.com/appscode/voyager/blob/release-3.2/docs/user-guide/ingress/configure-options.md
    #
    # Turn on per-request logging with:
    # "dontlog-normal": false
    # Turn off per-request logging with:
    # "dontlog-normal": true
    ingress.appscode.com/default-option: |
      {
        "dontlognull": "true",
        "dontlog-normal": "true",
        "log-separate-errors": "false",
        "http-server-close": "true",
        "clitcpka": "false"
      }

    ingress.appscode.com/max-connections: "16384"
```
and this is our `last-applied-annotations`:
```        ingress.appscode.com/last-applied-annotation-keys: ad.datadoghq.com/haproxy.check_names,ad.datadoghq.com/haproxy.init_configs,ad.datadoghq.com/haproxy.instances```

Comparing the different ReplicaSets, I do see the ordering or the last applied annotation keys changing. I'm guessing this difference is causing the problem?

**Comment by tamalsaha** [comment]
> I'm guessing this difference is causing the problem? 

Yeah. 8.0.0 fixes it.

**Comment by davinchia** [comment]
I'll give it a shot and update this issue. Thanks Tamal!
