### ISSUE TITLE
v12 release?

### ISSUE THREAD

**Issue by ajchiarello** [voyagermesh/voyager#1492]
I was wondering if there was any expected timeline for the release of v12 - it looks like there hasn't been a commit to this project for months, and I am beginning to wonder if it has been abandoned.

**Comment by joshk0** [comment]
I have had a pull request open for some time and am fearing the same. As Ingress support for Kubernetes has matured inside GCP, we are considering moving to Network Endpoint Groups + Global HTTPS Load Balancer pointing directly to our api-serving pods and removing haproxy entirely.

**Comment by tamalsaha** [comment]
Thanks for your patience. Can you test https://github.com/appscode/voyager/releases/tag/v12.0.0-rc.2 ?

**Comment by ajchiarello** [comment]
Well, the installation doesn't immediately fail, but when an ingress is created it fails because the tag on the haproxy image is haproxy, not 1.9.15-v12.0.0-rc.2-alpine. 

It seems like more often than not, the helm charts have breaking failures in them. We're now looking at how to move off voyager entirely because of these issues - you really need to improve your internal testing procedures before you can be considered a reliable project.

**Comment by ajchiarello** [comment]
And on top of it all, the haproxy.tag value in the helm chart is ignored by the application, which persists to try and change the haproxy tag to one that does not exist. 

Over the last year, I've installed five different versions of your helm chart. So far, only one has installed and operated correctly. Since that one working chart also contains a critical security vulnerability, and the replacement for it doesn't run properly, I am done trying to work with this product. I will figure out how to make NGINX, or Gloo, or Traefik, or one of the other ingress controllers out there do what I need.

**Comment by tamalsaha** [comment]
> Well, the installation doesn't immediately fail, but when an ingress is created it fails because the tag on the haproxy image is haproxy, not 1.9.15-v12.0.0-rc.2-alpine.

Can you please share what command you used to install the operator?

**Comment by ajchiarello** [comment]
I used the helm chart and upgraded my existing installation.

**Comment by tamalsaha** [comment]
What command did you run to upgrade?

**Comment by ajchiarello** [comment]
I manage my clusters with terraform, and updated the chart version in my code. This triggered the helm provider in terraform to install the updated chart. You can find information about the helm provider for terraform here: https://github.com/terraform-providers/terraform-provider-helm

**Comment by tamalsaha** [comment]
https://github.com/voyagermesh/voyager/releases/tag/v12.0.0

**Comment by tamalsaha** [comment]
@ajchiarello , the bug you reported should be fixed by https://github.com/voyagermesh/voyager/pull/1503
