### ISSUE TITLE
Deployment and Service not being creating

### ISSUE THREAD

**Issue by samispurs** [voyagermesh/voyager#1581]
Cannot create a aws lb, the configmap creates ok, but the deployment and service are not being created. version 9.0.0
Not much information in logs on why its not being created. 

DeploymentReconcileFailed      ingress/haproxy-ingress   Failed to reconcile HAProxy Deployment voyager-haproxy-ingress, Reason: the server could not find the requested resource

I0317 14:21:42.363968       1 workload.go:574] Creating apps/v1beta1, Kind=Deployment staging/voyager-haproxy-ingress.
E0317 14:21:42.365009       1 worker.go:76] Failed to process key staging/haproxy-ingress. Reason: the server could not find the requested resource
E0317 14:21:42.365027       1 worker.go:90] the server could not find the requested resource
I0317 14:21:42.365033       1 worker.go:91] Dropping key "staging/haproxy-ingress" out of the queue: the server could not find the requested resource

**Comment by seanwinterberger** [comment]
I believe the problem is this old version of voyager is attempting to make a deployment with the wrong `apiVersion`,  [back when deployments were beta](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/).  Either switch to voyager v11.0.0+ or decrement your k8s version.
