### ISSUE TITLE
stats pod not being created on EKS cluster 1.19 with v12.0.0

### ISSUE THREAD

**Issue by samispurs** [voyagermesh/voyager#1594]
voyager-operator pod not creating any stats pod, but does create a stats service.

I0831 14:06:39.792116       1 service.go:35] Creating Service qa/voyager-haproxy-ingress-stats.

lots of msgs spamming the logs with.
W0830 18:20:44.719198       1 loadbalancer.go:236] failed to delete old monitoring agent, reason: failed to get agent type: not found

**Comment by sFrenkie** [comment]
@samispurs how did you solve this? I've hit the same issue.

**Comment by samispurs** [comment]
@sFrenkie I have since upgraded the the version, but I believe a stats pod is not created if the cloud provider is anything but minikube.  I got the the stats page by port forwarding to port 56789 on the ingress controller (voyager-haproxy-ingress-xxxxxx-xxx) created in the namespace its created under.  e.g.
(kubectl port-forward voyager-haproxy-ingress-65946c8b-b77gw -n dev 56789:56789)
