### ISSUE TITLE
Any way to view generated HAProxy configs?

### ISSUE THREAD

**Issue by sokoow** [voyagermesh/voyager#752]
Hey All,

After we create an ingress, is there any way to view what haproxy configs are being created ? We are profiicient in haproxy, so wanted to see how you guys do your configs and what haproxy does under the hood. 

Greetings, Karol

**Comment by sadlil** [comment]
Yes. You can go to your kube-dashboard and Check for ConfigMap named like `voyager-<ing-name>`. Or use `kubectl get cm`. You can also exec into the pods and see `cat /etc/haproxy/haproxy.cfg`
