### ISSUE TITLE
Letsencrypt certs are being issued by duplicates 

### ISSUE THREAD

**Issue by evangelinaf** [voyagermesh/voyager#933]
Hello, using Voyager we are seeing that the certs are being issued duplicated for each domain, which causes to reach the Letsencrypt limit rate really fast. Checking both certs, the only difference I see is that one of them has Comodo as a operator, and the other one does not.
Voyager operator version that we are using is 5.0.0-rc.11.
Thank you.

**Comment by tamalsaha** [comment]
Example: https://crt.sh/?q=slack.appscode.com

I just issued a certificate. I am not seeing anything.

**Comment by tamalsaha** [comment]
Now, Voyager uses cert-manager.
